apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-telegram-bot
  template:
    metadata:
      labels:
        app: admin-telegram-bot
    spec:
      containers:
        - name: admin-telegram-bot
          image: <IMAGE-ADMIN-BOT>
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-api-admin-test-key
                  key: API_KEY
            - name: USER_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-api-test-key
                  key: API_KEY
            - name: ALLOWED_USER_IDS
              valueFrom:
                secretKeyRef:
                  name: allowed-users
                  key: ALLOWED_USER_IDS